from __future__ import annotations

from src.strings import get_bundle

REQUIRED_KEYS = [
    # Invite / registration
    "INVITE_CREATED_FMT",
    "INVITE_EXPIRES_FMT",
    "INVITE_NOT_FOUND",
    "INVITE_EXPIRED",
    "INVITE_ALREADY_USED",
    "INVITE_ALREADY_MASTER",
    "REGISTER_ASK_SPECIALTY",
    "REGISTER_SPECIALTY_HINT_HAIR",
    "REGISTER_SPECIALTY_HINT_DENTIST",
    "REGISTER_SPECIALTY_HINT_NAILS",
    "REGISTER_SPECIALTY_HINT_COSMETOLOGIST",
    "REGISTER_SPECIALTY_HINT_CUSTOM",
    "REGISTER_SLUG_CONFIRM_FMT",
    "REGISTER_SLUG_USE_BTN",
    "REGISTER_SLUG_CHANGE_BTN",
    "REGISTER_ASK_CUSTOM_SLUG",
    "REGISTER_SLUG_TAKEN",
    "REGISTER_SLUG_INVALID",
    "REGISTER_SLUG_RESERVED",
    "MAIN_MENU_MY_LINK",
    "MY_LINK_MSG_FMT",
    "MY_INVITES_EMPTY",
    "MY_INVITES_HEADER",
    "MY_INVITES_ITEM_FMT",
    "MY_INVITES_STATUS_ACTIVE",
    "MY_INVITES_STATUS_USED",
    "MY_INVITES_STATUS_EXPIRED",
    "NEW_INVITE_BTN",
    "SETTINGS_BTN_MY_LINK",
    "SETTINGS_BTN_MY_INVITES",
    "SETTINGS_BTN_NEW_INVITE",
    "SETTINGS_BTN_PROFILE",
    "SETTINGS_BTN_ADMIN",
    "PROFILE_MENU_TITLE",
    "PROFILE_BTN_NAME",
    "PROFILE_BTN_SPECIALTY",
    "PROFILE_BTN_SLUG",
    "PROFILE_ASK_NEW_NAME",
    "PROFILE_ASK_NEW_SPECIALTY",
    "PROFILE_ASK_NEW_SLUG",
    "PROFILE_UPDATED",
    "CLIENT_CATALOG_HEADER",
    "CLIENT_CATALOG_EMPTY",
    "CLIENT_CATALOG_CARD_FMT",
    "CLIENT_CATALOG_PICK_BTN",
    "CLIENT_MASTER_NOT_FOUND",
    "CLIENT_MASTER_CARD_FMT",
    "CLIENT_BOOK_HERE_BTN",
    "MASTER_BLOCKED_BANNER",
    "CLIENT_APPT_REJECTED_BLOCK",
    "ADMIN_MENU_TITLE",
    "ADMIN_MENU_MASTERS",
    "ADMIN_MENU_STATS",
    "ADMIN_MENU_INVITES",
    "ADMIN_MENU_MODERATION",
    "ADMIN_MENU_BACK",
    "ADMIN_MASTERS_HEADER",
    "ADMIN_MASTERS_EMPTY",
    "ADMIN_MASTER_ITEM_FMT",
    "ADMIN_MASTER_STATUS_ACTIVE",
    "ADMIN_MASTER_STATUS_BLOCKED",
    "ADMIN_BLOCK_BTN",
    "ADMIN_UNBLOCK_BTN",
    "ADMIN_BLOCK_DONE_FMT",
    "ADMIN_UNBLOCK_DONE_FMT",
    "ADMIN_STATS_FMT",
    "ADMIN_INVITES_HEADER",
    "ADMIN_INVITE_ITEM_FMT",
    "ADMIN_MASTER_NOT_FOUND",
]


def test_ru_bundle_has_all_epic9_keys() -> None:
    ru = get_bundle("ru")
    missing = [k for k in REQUIRED_KEYS if not hasattr(ru, k)]
    assert not missing, f"Missing RU keys: {missing}"


def test_hy_bundle_has_all_epic9_keys() -> None:
    hy = get_bundle("hy")
    missing = [k for k in REQUIRED_KEYS if not hasattr(hy, k)]
    assert not missing, f"Missing HY keys: {missing}"
