"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-04-20 20:05:58.711216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('masters',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('timezone', sa.Text(), server_default='Asia/Yerevan', nullable=False),
    sa.Column('work_hours', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('breaks', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('slot_step_min', sa.Integer(), server_default='20', nullable=False),
    sa.Column('auto_confirm', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('lang', sa.Text(), server_default='ru', nullable=False),
    sa.Column('decision_timeout_min', sa.Integer(), server_default='120', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_table('clients',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('master_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['masters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('master_id', 'phone', name='uq_clients_master_phone')
    )
    op.create_index('ix_clients_master_tg', 'clients', ['master_id', 'tg_id'], unique=False, postgresql_where=sa.text('tg_id IS NOT NULL'))
    op.create_table('services',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('master_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('price_amd', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_min > 0', name='ck_services_duration_positive'),
    sa.ForeignKeyConstraint(['master_id'], ['masters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_services_master_active', 'services', ['master_id'], unique=False, postgresql_where=sa.text('active = true'))
    op.create_table('appointments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('master_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('start_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('decision_deadline', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('cancelled_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('cancelled_by', sa.Text(), nullable=True),
    sa.CheckConstraint("cancelled_by IS NULL OR cancelled_by IN ('client', 'master', 'system')", name='ck_appointments_cancelled_by'),
    sa.CheckConstraint("source IN ('client_request', 'master_manual')", name='ck_appointments_source'),
    sa.CheckConstraint("status IN ('pending', 'confirmed', 'rejected', 'cancelled', 'completed', 'no_show')", name='ck_appointments_status'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['master_id'], ['masters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_appointments_master_start', 'appointments', ['master_id', 'start_at'], unique=False)
    op.create_index('ix_appointments_pending_deadline', 'appointments', ['status', 'decision_deadline'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_index('uq_appointment_slot', 'appointments', ['master_id', 'start_at'], unique=True, postgresql_where=sa.text("status IN ('pending', 'confirmed')"))
    op.create_table('reminders',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('send_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('channel', sa.Text(), server_default='telegram', nullable=False),
    sa.Column('sent', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("channel IN ('telegram', 'sms')", name='ck_reminders_channel'),
    sa.CheckConstraint("kind IN ('day_before', 'two_hours', 'master_morning')", name='ck_reminders_kind'),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reminders_pending_send_at', 'reminders', ['send_at'], unique=False, postgresql_where=sa.text('sent = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reminders_pending_send_at', table_name='reminders', postgresql_where=sa.text('sent = false'))
    op.drop_table('reminders')
    op.drop_index('uq_appointment_slot', table_name='appointments', postgresql_where=sa.text("status IN ('pending', 'confirmed')"))
    op.drop_index('ix_appointments_pending_deadline', table_name='appointments', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index('ix_appointments_master_start', table_name='appointments')
    op.drop_table('appointments')
    op.drop_index('ix_services_master_active', table_name='services', postgresql_where=sa.text('active = true'))
    op.drop_table('services')
    op.drop_index('ix_clients_master_tg', table_name='clients', postgresql_where=sa.text('tg_id IS NOT NULL'))
    op.drop_table('clients')
    op.drop_table('masters')
    # ### end Alembic commands ###
