# ruff: noqa: RUF001, E501
# cSpell:disable
from __future__ import annotations

from contextvars import ContextVar
from types import SimpleNamespace
from typing import Any

# Supported languages. `masters.lang` CHECKs against this set.
SUPPORTED_LANGS: frozenset[str] = frozenset({"ru", "hy"})
DEFAULT_LANG = "ru"

_current_lang: ContextVar[str] = ContextVar("current_lang", default=DEFAULT_LANG)


def set_current_lang(lang: str) -> None:
    """Called by LangMiddleware for each incoming update."""
    _current_lang.set(lang if lang in SUPPORTED_LANGS else DEFAULT_LANG)


def get_current_lang() -> str:
    return _current_lang.get()


_RU: dict[str, Any] = {
    "LANG_PICK_PROMPT": "Выберите язык / Ընտրեք լեզուն",
    "LANG_BTN_RU": "🇷🇺 Русский",
    "LANG_BTN_HY": "🇦🇲 Հայերեն",
    "REGISTER_WELCOME": "Добро пожаловать! Давайте настроим ваш профиль мастера.",
    "REGISTER_ASK_NAME": "Как к вам обращаться? (имя, как его увидят клиенты)",
    "REGISTER_ASK_PHONE": "Укажите телефон для связи.",
    "REGISTER_DONE": "Готово! Профиль создан. Что дальше?",
    "START_WELCOME_BACK": "С возвращением. Что дальше?",
    "MAIN_MENU_TODAY": "📅 Сегодня",
    "MAIN_MENU_ADD": "➕ Добавить запись",
    "MAIN_MENU_CALENDAR": "🗓 Календарь",
    "MAIN_MENU_SETTINGS": "⚙️ Настройки",
    "MAIN_MENU_TOMORROW": "📋 Завтра",
    "MAIN_MENU_WEEK": "🗓 Неделя",
    "MAIN_MENU_CLIENT": "🔎 Поиск клиента",
    "SETTINGS_MENU_TITLE": "Настройки",
    "SETTINGS_BTN_SERVICES": "Услуги",
    "SETTINGS_BTN_WORK_HOURS": "Часы работы",
    "SETTINGS_BTN_BREAKS": "Перерывы",
    "SETTINGS_BTN_LANGUAGE": "Язык",
    "LANGUAGE_PICK_PROMPT": "Выберите язык:",
    "LANGUAGE_CHANGED": "Язык переключён ✅",
    "SERVICES_EMPTY": "Услуг пока нет. Добавьте первую. Примеры: Чистка, Пломба, Стрижка.",
    "SERVICES_LIST_TITLE": "Ваши услуги:",
    "SERVICES_ITEM_FMT": "{name} · {duration} мин",
    "SERVICES_BTN_ADD": "➕ Добавить услугу",
    "SERVICES_BTN_EDIT": "✏️",
    "SERVICES_BTN_DELETE": "🗑",
    "SERVICES_ADD_ASK_NAME": "Название услуги?",
    "SERVICES_ADD_PICK_PRESET": "Выберите услугу или введите своё:",
    "SERVICES_ADD_CUSTOM_BTN": "✏️ Своё",
    "SERVICE_PRESET_CLEANING": "Чистка",
    "SERVICE_PRESET_FILLING": "Пломба",
    "SERVICE_PRESET_EXTRACTION": "Удаление",
    "SERVICE_PRESET_WHITENING": "Отбеливание",
    "SERVICE_PRESET_CROWN": "Коронка",
    "SERVICE_PRESET_HAIRCUT": "Стрижка",
    "SERVICE_PRESET_COLORING": "Окрашивание",
    "SERVICE_PRESET_STYLING": "Укладка",
    "SERVICE_PRESET_BEARD": "Борода",
    "SERVICE_PRESET_HIGHLIGHTS": "Мелирование",
    "SERVICE_PRESET_MANICURE": "Маникюр",
    "SERVICE_PRESET_PEDICURE": "Педикюр",
    "SERVICE_PRESET_GEL": "Гель-лак",
    "SERVICE_PRESET_NAIL_EXT": "Наращивание",
    "SERVICE_PRESET_FACE_CLEANING": "Чистка лица",
    "SERVICE_PRESET_PEELING": "Пилинг",
    "SERVICE_PRESET_MASSAGE": "Массаж",
    "SERVICE_PRESET_BOTOX": "Ботокс",
    "SERVICES_ADD_ASK_DURATION": "Длительность в минутах? (целое число)",
    "SERVICES_ADD_BAD_DURATION": "Нужно целое число минут больше нуля.",
    "SERVICES_ADDED": "Услуга добавлена.",
    "SERVICES_DELETED": "Услуга удалена.",
    "SERVICES_EDIT_MENU": "Что меняем?",
    "SERVICES_EDIT_BTN_NAME": "Название",
    "SERVICES_EDIT_BTN_DURATION": "Длительность",
    "SERVICES_EDIT_BTN_TOGGLE": "Вкл/выкл",
    "SERVICES_EDIT_NAME_PROMPT": "Новое название?",
    "SERVICES_EDIT_DURATION_PROMPT": "Новая длительность в минутах?",
    "SERVICES_UPDATED": "Услуга обновлена.",
    "SERVICES_BTN_BACK": "← назад",
    "WORK_HOURS_TITLE": "Часы работы по дням недели:",
    "WORK_HOURS_DAY_OFF": "выходной",
    "WORK_HOURS_PICK_DAY": "Выберите день:",
    "WORK_HOURS_ASK_START": "Начало рабочего дня? Формат HH:MM, например 10:00.",
    "WORK_HOURS_ASK_END": "Конец рабочего дня? Формат HH:MM, например 19:00.",
    "WORK_HOURS_BAD_FORMAT": "Не разобрал. Ожидаю HH:MM, например 10:00.",
    "WORK_HOURS_BAD_ORDER": "Конец должен быть позже начала.",
    "WORK_HOURS_BTN_DAY_OFF": "Выходной",
    "WORK_HOURS_BTN_BACK": "← Назад",
    "WORK_HOURS_SAVED": "Сохранено.",
    "WORK_HOURS_BTN_DONE": "Готово",
    "WORK_HOURS_PICK_START": "{day}: когда начинаете?",
    "WORK_HOURS_PICK_END": "{day}: начало {start}. Когда заканчиваете?",
    "WEEKDAYS": {
        "mon": "Пн",
        "tue": "Вт",
        "wed": "Ср",
        "thu": "Чт",
        "fri": "Пт",
        "sat": "Сб",
        "sun": "Вс",
    },
    "SECTION_COMING_SOON": "Раздел «{section}» — скоро.",
    # --- Epic 4: client booking ---
    "CLIENT_START_NO_MASTER": "Бот пока не настроен. Попросите мастера запустить его.",
    "CLIENT_CHOOSE_SERVICE": "Выберите услугу:",
    "CLIENT_NO_SERVICES": "У мастера пока нет услуг. Попробуйте позже.",
    "CLIENT_CHOOSE_DATE": "Выберите дату:",
    "CLIENT_CHOOSE_TIME": "Свободные слоты на {date}:",
    "CLIENT_NO_SLOTS": "На этот день свободных слотов нет. Выберите другую дату.",
    "CLIENT_ASK_NAME": "Как вас зовут?",
    "CLIENT_BAD_NAME": "Пожалуйста, введите имя (1–60 символов).",
    "CLIENT_ASK_PHONE": "Телефон в формате +374 XX XXX XXX:",
    "CLIENT_BAD_PHONE": "Не разобрал номер. Пример: +374 99 123 456",
    "CLIENT_CONFIRM_TITLE": (
        "📋 Проверьте запись:\n"
        "🧑\u200d⚕️ Услуга: {service}\n"
        "📅 {date} в {time}\n"
        "👤 {name}\n"
        "📞 {phone}\n\n"
        "Подтвердить?"
    ),
    "CLIENT_BTN_CONFIRM": "✅ Подтвердить",
    "CLIENT_BTN_CANCEL": "❌ Отменить",
    "CLIENT_BTN_BACK": "← Назад",
    "CLIENT_SENT": "Заявка отправлена мастеру. Ждите подтверждения.",
    "CLIENT_CANCELLED": "Запись отменена.",
    "CLIENT_BOOK_AGAIN_BTN": "📅 Записаться ещё раз",
    "CLIENT_SLOT_TAKEN": "Этот слот только что заняли. Выберите другое время.",
    "CLIENT_APPT_PENDING": (
        "✅ Заявка отправлена\n"
        "📅 {date} в {time} — {service}\n\n"
        "Ждём подтверждения от мастера — пришлём уведомление, когда подтвердит."
    ),
    "CLIENT_APPT_CONFIRMED": "Мастер подтвердил вашу запись на {date} в {time}. До встречи!",
    "CLIENT_APPT_REJECTED": "К сожалению, мастер отклонил запись на {date} в {time}.",
    # --- Epic 4: master approval ---
    "APPT_NOTIFY_MASTER": (
        "🔔 Новая заявка\n"
        "🧑 {name}\n"
        "📞 {phone}\n"
        "🧑\u200d⚕️ {service} ({duration} мин)\n"
        "📅 {date} в {time} ({weekday})"
    ),
    "APPT_BTN_CONFIRM": "✅ Подтвердить",
    "APPT_BTN_REJECT": "❌ Отклонить",
    "MASTER_APPT_CONFIRMED_AFTER": "✅ Запись подтверждена",
    "MASTER_APPT_REJECTED_AFTER": "❌ Запись отклонена",
    "APPT_BTN_HISTORY": "📋 История клиента",
    "APPT_ALREADY_PROCESSED": "Эта заявка уже обработана.",
    "APPT_CONFIRMED_STAMP": "\n\n✅ Подтверждено в {time}",
    "APPT_REJECTED_STAMP": "\n\n❌ Отклонено в {time}",
    "APPT_HISTORY_TITLE": "История клиента {name} (последние {limit}):",
    "APPT_HISTORY_LINE": "• {date} {time} — {service} — {status}",
    "APPT_HISTORY_EMPTY": "У клиента пока нет истории записей.",
    "APPT_STATUS_CONFIRMED": "✅ подтверждено",
    "APPT_STATUS_CANCELLED": "❌ отменено",
    "APPT_STATUS_REJECTED": "❌ отклонено",
    "APPT_STATUS_COMPLETED": "☑️ завершено",
    "APPT_STATUS_NO_SHOW": "⚠️ не пришёл",
    "MONTH_NAMES": [
        "Январь",
        "Февраль",
        "Март",
        "Апрель",
        "Май",
        "Июнь",
        "Июль",
        "Август",
        "Сентябрь",
        "Октябрь",
        "Ноябрь",
        "Декабрь",
    ],
    "WEEKDAY_SHORT": ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"],
    # --- Epic 5: master manual add ---
    "MANUAL_PICK_CLIENT": "Выбери клиента или создай нового:",
    "MANUAL_NO_RECENT": "Ещё нет клиентов. Нажми ➕ Новый.",
    "MANUAL_SEARCH_PROMPT": "Введи 2+ символа (имя или телефон):",
    "MANUAL_SEARCH_EMPTY": "Ничего не нашёл. Попробуй ещё.",
    "MANUAL_ASK_NAME": "Имя клиента:",
    "MANUAL_NAME_BAD": "Минимум 2 символа. Попробуй ещё.",
    "MANUAL_ASK_PHONE": "Телефон клиента (+374XXXXXXXX):",
    "MANUAL_PHONE_BAD": "Формат: +374XXXXXXXX. Попробуй ещё.",
    "MANUAL_PHONE_DUP": "По этому номеру уже есть клиент «{name}». Использовать его?",
    "MANUAL_ASK_SERVICE": "Выбери услугу:",
    "MANUAL_ASK_DATE": "Выбери дату:",
    "MANUAL_ASK_SLOT": "Выбери время или введи нестандартное:",
    "MANUAL_CUSTOM_PROMPT": (
        "Введи дату и время: ДД.ММ ЧЧ:ММ (или только ЧЧ:ММ для выбранной даты):"
    ),
    "MANUAL_CUSTOM_BAD": "Неверный формат. Пример: 25.04 14:30",
    "MANUAL_CUSTOM_PAST": "Нельзя в прошлое. Выбери другое время.",
    "MANUAL_ASK_COMMENT": "Комментарий (или нажми ⏭ Пропустить):",
    "MANUAL_CONFIRM_CARD": (
        "Подтверди запись:\n👤 {client}\n📞 {phone}\n💇 {service}\n📅 {date} {time}\n📝 {notes}"
    ),
    "MANUAL_SAVED": "✅ Запись сохранена.",
    "MANUAL_CANCELED": "Отменено.",
    "MANUAL_SLOT_TAKEN": "Этот слот только что занят. Выбери другой.",
    "MANUAL_BTN_SEARCH": "🔍 Поиск",
    "MANUAL_BTN_NEW": "➕ Новый",
    "MANUAL_BTN_SEARCH_CANCEL": "⬅ Отмена поиска",
    "MANUAL_BTN_DUP_USE": "Да, использовать",
    "MANUAL_BTN_DUP_RETRY": "Отмена — ввести другой",
    "MANUAL_BTN_CUSTOM_TIME": "➕ Нестандартное время",
    "MANUAL_BTN_BACK": "⬅ Назад",
    "MANUAL_BTN_SKIP": "⏭ Пропустить",
    "MANUAL_BTN_SAVE": "✅ Сохранить",
    "MANUAL_BTN_CANCEL": "❌ Отмена",
    # --- client-side cancellation + notification ---
    "CLIENT_NOTIFY_MANUAL": "Врач записал вас на {date} {time} — {service}.",
    "CLIENT_CANCEL_BUTTON": "❌ Отменить запись",
    "CLIENT_CANCEL_DONE": "Запись отменена.",
    "CLIENT_CANCEL_UNAVAILABLE": "Запись уже недоступна.",
    "MASTER_NOTIFY_CLIENT_CANCELED": "Клиент {name} отменил запись: {date} {time} — {service}.",
    # --- Epic 6: schedule views ---
    "SCHED_DAY_HEADER": "📅 {weekday} {dd} {mon}",
    "SCHED_WORK_HOURS_LINE": "🕐 Рабочие часы: {start}–{end}",
    "SCHED_DAY_OFF_LINE": "🕐 Сегодня выходной",
    "SCHED_APPTS_SECTION": "\n📋 Записи ({count}):",
    "SCHED_APPTS_EMPTY": "\n📋 Записей нет.",
    "SCHED_APPT_LINE": "{emoji} {time}  {client} · {service}",
    "SCHED_FREE_SECTION": "\n🆓 Свободно:",
    "SCHED_FREE_NONE": "\n🆓 Свободных слотов нет.",
    "SCHED_STATUS_PENDING": "⏳",
    "SCHED_STATUS_CONFIRMED": "✅",
    "SCHED_STATUS_COMPLETED": "✅",
    "SCHED_STATUS_NO_SHOW": "❌",
    "DAY_NAV_TODAY": "⬅ Сегодня",
    "DAY_NAV_TOMORROW": "📅 Завтра",
    "DAY_NAV_WEEK": "🗓 Неделя",
    "DAY_NAV_CALENDAR": "🗓 Календарь",
    "DAY_NAV_ADD": "➕ Добавить",
    "DAY_NAV_BACK_TO_WEEK": "⬅ Назад в неделю",
    "DAY_NAV_BACK_TO_CALENDAR": "⬅ Назад в календарь",
    "MARK_PAST_PRESENT": "✅ {time} {short}",
    "MARK_PAST_NO_SHOW": "❌ {time} {short}",
    "MASTER_CANCEL_BTN": "❌ {time} {short}",
    "MASTER_CANCEL_ASK_FMT": ("Отменить запись?\n\n👤 {client}\n💇 {service}\n📅 {date} в {time}"),
    "MASTER_CANCEL_BTN_CONFIRM": "✅ Да, отменить",
    "MASTER_CANCEL_BTN_ABORT": "← Нет",
    "MASTER_CANCEL_DONE": "Запись отменена ✅",
    "MASTER_CANCEL_UNAVAILABLE": "Запись уже нельзя отменить.",
    "CLIENT_APPT_CANCELLED_BY_MASTER": (
        "Мастер отменил вашу запись на {date} в {time} — {service}.\n"
        "Если хотите выбрать другое время: {link}"
    ),
    "MARK_PAST_OK_COMPLETED": "Отмечено: был",
    "MARK_PAST_OK_NO_SHOW": "Отмечено: не пришёл",
    "MARK_PAST_NOT_AVAILABLE": "Запись недоступна",
    "MARK_PAST_NOT_ENDED": "Ещё не закончилась",
    "MARK_PAST_ALREADY_CLOSED": "Уже помечена",
    "WEEK_HEADER": "🗓 Неделя с {dd} {mon}",
    "WEEK_DAY_LINE": "{wd} {dd}.{mm}  {count} зап  {bar}  {pct}%",
    "WEEK_DAY_LINE_OFF": "{wd} {dd}.{mm}  выходной  {bar}",
    "WEEK_BTN_DAY": "{wd} {dd}",
    "CLIENT_SEARCH_PROMPT": "Имя или телефон клиента:",
    "CLIENT_SEARCH_TOO_SHORT": "Минимум 2 символа. Попробуй ещё.",
    "CLIENT_SEARCH_EMPTY": "Никого не нашёл. Попробуй ещё.",
    "CLIENT_PAGE_HEADER": "👤 {name}\n📞 {phone}",
    "CLIENT_PAGE_NOTES_TITLE": "\n\n📝 Заметки:\n{notes}",
    "CLIENT_PAGE_NOTES_EMPTY": "_не указано_",
    "CLIENT_PAGE_HISTORY_TITLE": "\n\n📊 История ({count} записей):",
    "CLIENT_PAGE_HISTORY_EMPTY": "\n\n📊 Истории пока нет.",
    "CLIENT_PAGE_HISTORY_LINE": "{emoji} {dd}.{mm}  {time}  {service}{suffix}",
    "CLIENT_PAGE_HISTORY_MORE": "…и ещё {n}",
    "CLIENT_PAGE_SUFFIX_FUTURE": " · будущая",
    "CLIENT_PAGE_SUFFIX_CANCELLED": " · отменена",
    "CLIENT_PAGE_SUFFIX_REJECTED": " · отклонена",
    "CLIENT_PAGE_BTN_EDIT_NOTES": "✏️ Редактировать заметки",
    "CLIENT_PAGE_BTN_ADD_APPT": "➕ Добавить запись",
    "CLIENT_PAGE_NOT_FOUND": "Клиент не найден.",
    "CLIENT_NOTES_PROMPT": "Новые заметки (или отправь `-` чтобы очистить):",
    "CLIENT_NOTES_SAVED": "Сохранено.",
    # --- Epic 7: reminders ---
    "REMINDER_CLIENT_DAY_BEFORE": "⏰ Напоминание: завтра в {time} — {service}.\nЖдём вас!",
    "REMINDER_CLIENT_TWO_HOURS": "⏰ Через 2 часа у вас запись: {service}, {time}.",
    "REMINDER_MASTER_BEFORE": "⏰ Сейчас {time}: {client_name} — {service}.\n📞 {phone}",
    "REMINDER_PENDING_EXPIRED": (
        "К сожалению, мастер не подтвердил вашу заявку на {date} {time} — {service}.\n"
        "Попробуйте выбрать другое время: {link}"
    ),
    # --- Epic 9: multi-master ---
    "INVITE_CREATED_FMT": "Инвайт создан.\n\nКод: `{code}`\nСсылка: {link}\n\nДействителен до: {expires}",
    "INVITE_EXPIRES_FMT": "до {date}",
    "INVITE_NOT_FOUND": "Код инвайта не найден.",
    "INVITE_EXPIRED": "Код инвайта истёк. Попросите новый.",
    "INVITE_ALREADY_USED": "Этот код уже использован.",
    "INVITE_ALREADY_MASTER": "Вы уже зарегистрированы как мастер.",
    "REGISTER_ASK_SPECIALTY": "Кто вы по специальности? Нажмите кнопку-подсказку или напишите своё:",
    "REGISTER_SPECIALTY_HINT_HAIR": "💈 Парикмахер",
    "REGISTER_SPECIALTY_HINT_DENTIST": "🦷 Стоматолог",
    "REGISTER_SPECIALTY_HINT_NAILS": "💅 Мастер маникюра",
    "REGISTER_SPECIALTY_HINT_COSMETOLOGIST": "💆 Косметолог",
    "REGISTER_SPECIALTY_HINT_CUSTOM": "✏️ Своё",
    "REGISTER_SLUG_CONFIRM_FMT": "Ваша ссылка будет:\nt.me/{username}?start=master_{slug}\n\nИспользовать?",
    "REGISTER_SLUG_USE_BTN": "✅ Использовать",
    "REGISTER_SLUG_CHANGE_BTN": "✏️ Изменить",
    "REGISTER_ASK_CUSTOM_SLUG": "Введите адрес (только латиница, цифры, дефис, 3–32 символа):",
    "REGISTER_SLUG_TAKEN": "Этот адрес уже занят. Попробуйте другой.",
    "REGISTER_SLUG_INVALID": "Адрес должен быть из латиницы, цифр и дефисов (3–32).",
    "REGISTER_SLUG_RESERVED": "Этот адрес зарезервирован. Выберите другой.",
    "MAIN_MENU_MY_LINK": "🔗 Моя ссылка",
    "MAIN_MENU_QR": "📱 QR-код",
    "MY_LINK_MSG_FMT": "Ваша ссылка для клиентов:\n{link}\n\nПоделитесь ею в соцсетях или с клиентами напрямую.",
    "QR_CAPTION_FMT": "📱 QR-код вашей ссылки.\n\n{link}\n\nРаспечатайте и приклейте в салоне — клиенты отсканируют и сразу попадут в бота.",
    "MY_INVITES_EMPTY": "Вы пока не создавали инвайтов.",
    "MY_INVITES_HEADER": "Ваши инвайты:",
    "MY_INVITES_ITEM_FMT": "`{code}` · {status} · {expires}",
    "MY_INVITES_STATUS_ACTIVE": "активен",
    "MY_INVITES_STATUS_USED": "использован",
    "MY_INVITES_STATUS_EXPIRED": "просрочен",
    "NEW_INVITE_BTN": "➕ Пригласить мастера",
    "SETTINGS_BTN_MY_LINK": "🔗 Моя ссылка",
    "SETTINGS_BTN_MY_INVITES": "📨 Мои инвайты",
    "SETTINGS_BTN_NEW_INVITE": "➕ Пригласить мастера",
    "SETTINGS_BTN_PROFILE": "👤 Мой профиль",
    "SETTINGS_BTN_ADMIN": "🛠 Админ",
    "PROFILE_MENU_TITLE": "Что изменить?",
    "PROFILE_BTN_NAME": "✏️ Имя",
    "PROFILE_BTN_SPECIALTY": "✏️ Специальность",
    "PROFILE_BTN_SLUG": "✏️ Адрес (slug)",
    "PROFILE_ASK_NEW_NAME": "Введите новое имя:",
    "PROFILE_ASK_NEW_SPECIALTY": "Введите специальность:",
    "PROFILE_ASK_NEW_SLUG": "Введите новый адрес (3–32 символа, a-z0-9-):",
    "PROFILE_UPDATED": "Готово ✅",
    "CLIENT_CATALOG_HEADER": "Выберите мастера:",
    "CLIENT_CATALOG_EMPTY": "Мастера пока не зарегистрированы.",
    "CLIENT_CATALOG_CARD_FMT": "👤 {name} — {specialty}",
    "CLIENT_CATALOG_PICK_BTN": "📅 Записаться",
    "CLIENT_MASTER_NOT_FOUND": "Мастер не найден.",
    "CLIENT_MASTER_CARD_FMT": "👤 {name}\n{specialty}",
    "CLIENT_BOOK_HERE_BTN": "📅 Записаться",
    "MASTER_BLOCKED_BANNER": "⛔ Ваш кабинет временно заблокирован администратором.",
    "CLIENT_APPT_REJECTED_BLOCK": "К сожалению, мастер временно недоступен. Ваша заявка отменена.",
    "ADMIN_MENU_TITLE": "Админ-меню:",
    "ADMIN_MENU_MASTERS": "👥 Мастера",
    "ADMIN_MENU_STATS": "📊 Статистика",
    "ADMIN_MENU_INVITES": "📨 Инвайты",
    "ADMIN_MENU_MODERATION": "🛠 Модерация",
    "ADMIN_MENU_BACK": "⬅️ В главное меню",
    "ADMIN_MASTERS_HEADER": "Все мастера:",
    "ADMIN_MASTERS_EMPTY": "Мастеров пока нет.",
    "ADMIN_MASTER_ITEM_FMT": "`{slug}` · {name} · {status}",
    "ADMIN_MASTER_STATUS_ACTIVE": "активен",
    "ADMIN_MASTER_STATUS_BLOCKED": "заблокирован",
    "ADMIN_BLOCK_BTN": "🚫 Заблокировать",
    "ADMIN_UNBLOCK_BTN": "✅ Разблокировать",
    "ADMIN_BLOCK_DONE_FMT": "Мастер {slug} заблокирован. Отменено pending: {n}.",
    "ADMIN_UNBLOCK_DONE_FMT": "Мастер {slug} разблокирован.",
    "ADMIN_STATS_FMT": (
        "📊 Статистика\n\n"
        "Мастера: {masters_active} активных / {masters_blocked} заблокированных\n"
        "Клиентов (уникальных): {clients}\n"
        "Записей за 7 дней: {appt_7d}\n"
        "Записей за 30 дней: {appt_30d}"
    ),
    "ADMIN_INVITES_HEADER": "Все инвайты:",
    "ADMIN_INVITE_ITEM_FMT": "`{code}` · {status} · by {creator_tg_id}",
    "ADMIN_INVITE_NEW_SALON_BTN": "➕ Пригласить салон",
    "ADMIN_INVITE_SALON_CREATED_FMT": (
        "Инвайт салона создан.\n\nКод: `{code}`\nСсылка: {link}\nДействителен до: {expires}"
    ),
    "ADMIN_MASTER_NOT_FOUND": "Мастер с таким slug не найден.",
    "ADMIN_MASTER_DETAIL_REGISTERED": "Зарегистрирован",
    "ADMIN_MASTER_DETAIL_SPECIALTY": "Специальность",
    "ADMIN_MASTER_DETAIL_STATUS": "Статус",
    "ADMIN_MASTER_USAGE": "Использование: /master <slug>",
    # --- Epic 10.1: salon main menu ---
    "SALON_WELCOME_BACK": "С возвращением, салон. Что дальше?",
    "SALON_MENU_MY_MASTERS": "👥 Мои мастера",
    "SALON_MENU_INVITE_MASTER": "➕ Пригласить мастера",
    "SALON_MENU_ADD_APPT": "➕ Новая запись",
    "SALON_MENU_MY_LINK": "🔗 Моя ссылка",
    "SALON_MENU_QR": "📱 QR-код",
    "SALON_MENU_SETTINGS": "⚙️ Настройки",
}

_HY: dict[str, Any] = {
    "LANG_PICK_PROMPT": "Ընտրեք լեզուն / Выберите язык",
    "LANG_BTN_RU": "🇷🇺 Русский",
    "LANG_BTN_HY": "🇦🇲 Հայերեն",
    "REGISTER_WELCOME": "Բարի գալուստ։ Եկեք կարգավորենք ձեր վարպետի պրոֆիլը։",
    "REGISTER_ASK_NAME": "Ինչպե՞ս դիմել ձեզ (անունը, ինչպես հաճախորդները կտեսնեն)",
    "REGISTER_ASK_PHONE": "Նշեք կապի հեռախոսահամարը։",
    "REGISTER_DONE": "Պատրաստ է։ Պրոֆիլը ստեղծված է։ Ի՞նչ հետո։",
    "START_WELCOME_BACK": "Բարի վերադարձ։ Ի՞նչ հետո։",
    "MAIN_MENU_TODAY": "📅 Այսօր",
    "MAIN_MENU_ADD": "➕ Ավելացնել գրանցում",
    "MAIN_MENU_CALENDAR": "🗓 Օրացույց",
    "MAIN_MENU_SETTINGS": "⚙️ Կարգավորումներ",
    "MAIN_MENU_TOMORROW": "📋 Վաղը",
    "MAIN_MENU_WEEK": "🗓 Շաբաթ",
    "MAIN_MENU_CLIENT": "🔎 Որոնել հաճախորդ",
    "SETTINGS_MENU_TITLE": "Կարգավորումներ",
    "SETTINGS_BTN_SERVICES": "Ծառայություններ",
    "SETTINGS_BTN_WORK_HOURS": "Աշխատանքային ժամեր",
    "SETTINGS_BTN_BREAKS": "Ընդմիջումներ",
    "SETTINGS_BTN_LANGUAGE": "Լեզու",
    "LANGUAGE_PICK_PROMPT": "Ընտրեք լեզուն։",
    "LANGUAGE_CHANGED": "Լեզուն փոխվեց ✅",
    "SERVICES_EMPTY": (
        "Ծառայություններ դեռ չկան։ Ավելացրեք առաջինը։ Օրինակներ՝ Մաքրում, Լցոնում, Սանրվածք։"
    ),
    "SERVICES_LIST_TITLE": "Ձեր ծառայությունները։",
    "SERVICES_ITEM_FMT": "{name} · {duration} րոպե",
    "SERVICES_BTN_ADD": "➕ Ավելացնել ծառայություն",
    "SERVICES_BTN_EDIT": "✏️",
    "SERVICES_BTN_DELETE": "🗑",
    "SERVICES_ADD_ASK_NAME": "Ծառայության անունը՞",
    "SERVICES_ADD_PICK_PRESET": "Ընտրեք ծառայությունը կամ գրեք ձերը՝",
    "SERVICES_ADD_CUSTOM_BTN": "✏️ Սեփական տարբերակ",
    "SERVICE_PRESET_CLEANING": "Մաքրում",
    "SERVICE_PRESET_FILLING": "Պլոմբա",
    "SERVICE_PRESET_EXTRACTION": "Հեռացում",
    "SERVICE_PRESET_WHITENING": "Սպիտակեցում",
    "SERVICE_PRESET_CROWN": "Կորոնկա",
    "SERVICE_PRESET_HAIRCUT": "Սանրվածք",
    "SERVICE_PRESET_COLORING": "Ներկում",
    "SERVICE_PRESET_STYLING": "Հարդարում",
    "SERVICE_PRESET_BEARD": "Մորուք",
    "SERVICE_PRESET_HIGHLIGHTS": "Մելիրավորում",
    "SERVICE_PRESET_MANICURE": "Մանիկյուր",
    "SERVICE_PRESET_PEDICURE": "Պեդիկյուր",
    "SERVICE_PRESET_GEL": "Գել-լաք",
    "SERVICE_PRESET_NAIL_EXT": "Երկարացում",
    "SERVICE_PRESET_FACE_CLEANING": "Դեմքի մաքրում",
    "SERVICE_PRESET_PEELING": "Պիլինգ",
    "SERVICE_PRESET_MASSAGE": "Մերսում",
    "SERVICE_PRESET_BOTOX": "Բոտոքս",
    "SERVICES_ADD_ASK_DURATION": "Տևողությունը րոպեներով՞ (ամբողջ թիվ)",
    "SERVICES_ADD_BAD_DURATION": "Պետք է ամբողջ թիվ լինի՝ 0-ից մեծ։",
    "SERVICES_ADDED": "Ծառայությունը ավելացվեց։",
    "SERVICES_DELETED": "Ծառայությունը ջնջվեց։",
    "SERVICES_EDIT_MENU": "Ի՞նչ փոխենք։",
    "SERVICES_EDIT_BTN_NAME": "Անուն",
    "SERVICES_EDIT_BTN_DURATION": "Տևողություն",
    "SERVICES_EDIT_BTN_TOGGLE": "Միացնել/անջատել",
    "SERVICES_EDIT_NAME_PROMPT": "Նոր անունը՞",
    "SERVICES_EDIT_DURATION_PROMPT": "Նոր տևողությունը րոպեներով՞",
    "SERVICES_UPDATED": "Ծառայությունը թարմացվեց։",
    "SERVICES_BTN_BACK": "← հետ",
    "WORK_HOURS_TITLE": "Աշխատանքային ժամերը ըստ շաբաթվա օրերի։",
    "WORK_HOURS_DAY_OFF": "հանգստյան",
    "WORK_HOURS_PICK_DAY": "Ընտրեք օրը։",
    "WORK_HOURS_ASK_START": "Աշխատանքային օրվա սկիզբը՞ HH:MM ձևաչափով (օր. 10:00)",
    "WORK_HOURS_ASK_END": "Աշխատանքային օրվա ավարտը՞ HH:MM ձևաչափով (օր. 19:00)",
    "WORK_HOURS_BAD_FORMAT": "Չհասկացա։ Սպասվում է HH:MM (օր. 10:00)",
    "WORK_HOURS_BAD_ORDER": "Ավարտը պետք է ավելի ուշ լինի, քան սկիզբը։",
    "WORK_HOURS_BTN_DAY_OFF": "Հանգստյան օր",
    "WORK_HOURS_BTN_BACK": "← Հետ",
    "WORK_HOURS_SAVED": "Պահպանվեց։",
    "WORK_HOURS_BTN_DONE": "Պատրաստ է",
    "WORK_HOURS_PICK_START": "{day}: ե՞րբ եք սկսում։",
    "WORK_HOURS_PICK_END": "{day}: սկիզբը {start}. Ե՞րբ եք ավարտում։",
    "WEEKDAYS": {
        "mon": "Երկ",
        "tue": "Երք",
        "wed": "Չրք",
        "thu": "Հնգ",
        "fri": "Ուրբ",
        "sat": "Շաբ",
        "sun": "Կիր",
    },
    "SECTION_COMING_SOON": "«{section}» բաժինը՝ շուտով։",
    # --- Epic 4: client booking ---
    "CLIENT_START_NO_MASTER": "Բոտը դեռ կարգավորված չէ։ Խնդրեք վարպետին գործարկել այն։",
    "CLIENT_CHOOSE_SERVICE": "Ընտրեք ծառայությունը։",
    "CLIENT_NO_SERVICES": "Վարպետը դեռ ծառայություններ չունի։ Փորձեք ավելի ուշ։",
    "CLIENT_CHOOSE_DATE": "Ընտրեք ամսաթիվը։",
    "CLIENT_CHOOSE_TIME": "Ազատ ժամանակներ {date}-ին։",
    "CLIENT_NO_SLOTS": "Այս օրը ազատ ժամեր չկան։ Ընտրեք այլ ամսաթիվ։",
    "CLIENT_ASK_NAME": "Ինչպե՞ս է ձեր անունը։",
    "CLIENT_BAD_NAME": "Խնդրում ենք մուտքագրել անուն (1–60 սիմվոլ)։",
    "CLIENT_ASK_PHONE": "Հեռախոսը՝ +374 XX XXX XXX ձևաչափով։",
    "CLIENT_BAD_PHONE": "Չհասկացա համարը։ Օրինակ՝ +374 99 123 456",
    "CLIENT_CONFIRM_TITLE": (
        "📋 Ստուգեք գրանցումը:\n"
        "🧑\u200d⚕️ Ծառայություն՝ {service}\n"
        "📅 {date} {time}\n"
        "👤 {name}\n"
        "📞 {phone}\n\n"
        "Հաստատե՞լ"
    ),
    "CLIENT_BTN_CONFIRM": "✅ Հաստատել",
    "CLIENT_BTN_CANCEL": "❌ Չեղարկել",
    "CLIENT_BTN_BACK": "← Հետ",
    "CLIENT_SENT": "Հայտը ուղարկվել է վարպետին։ Սպասեք հաստատմանը։",
    "CLIENT_CANCELLED": "Գրանցումը չեղարկվեց։",
    "CLIENT_BOOK_AGAIN_BTN": "📅 Գրանցվել նորից",
    "CLIENT_SLOT_TAKEN": "Այս ժամը արդեն զբաղված է։ Ընտրեք այլ ժամանակ։",
    "CLIENT_APPT_PENDING": (
        "✅ Հայտը ուղարկված է\n"
        "📅 {date} {time} — {service}\n\n"
        "Սպասում ենք վարպետի հաստատմանը — կհայտնենք, երբ հաստատի։"
    ),
    "CLIENT_APPT_CONFIRMED": "Վարպետը հաստատեց ձեր գրանցումը {date} {time}-ին։ Կտեսնվենք։",
    "CLIENT_APPT_REJECTED": "Ցավոք, վարպետը մերժեց գրանցումը {date} {time}-ին։",
    # --- Epic 4: master approval ---
    "APPT_NOTIFY_MASTER": (
        "🔔 Նոր հայտ\n"
        "🧑 {name}\n"
        "📞 {phone}\n"
        "🧑\u200d⚕️ {service} ({duration} րոպե)\n"
        "📅 {date} {time} ({weekday})"
    ),
    "APPT_BTN_CONFIRM": "✅ Հաստատել",
    "APPT_BTN_REJECT": "❌ Մերժել",
    "APPT_BTN_HISTORY": "📋 Հաճախորդի պատմություն",
    "APPT_ALREADY_PROCESSED": "Այս հայտը արդեն մշակված է։",
    "APPT_CONFIRMED_STAMP": "\n\n✅ Հաստատված {time}-ին",
    "APPT_REJECTED_STAMP": "\n\n❌ Մերժված {time}-ին",
    "APPT_HISTORY_TITLE": "{name} հաճախորդի պատմություն (վերջին {limit})։",
    "APPT_HISTORY_LINE": "• {date} {time} — {service} — {status}",
    "APPT_HISTORY_EMPTY": "Հաճախորդը դեռ պատմություն չունի։",
    "APPT_STATUS_CONFIRMED": "✅ հաստատված",
    "APPT_STATUS_CANCELLED": "❌ չեղարկված",
    "APPT_STATUS_REJECTED": "❌ մերժված",
    "APPT_STATUS_COMPLETED": "☑️ ավարտված",
    "APPT_STATUS_NO_SHOW": "⚠️ չի եկել",
    "MONTH_NAMES": [
        "Հունվար",
        "Փետրվար",
        "Մարտ",
        "Ապրիլ",
        "Մայիս",
        "Հունիս",
        "Հուլիս",
        "Օգոստոս",
        "Սեպտեմբեր",
        "Հոկտեմբեր",
        "Նոյեմբեր",
        "Դեկտեմբեր",
    ],
    "WEEKDAY_SHORT": ["Երկ", "Երք", "Չրք", "Հնգ", "Ուրբ", "Շաբ", "Կիր"],
    # --- Epic 5: master manual add ---
    "MANUAL_PICK_CLIENT": "Ընտրիր հաճախորդին կամ ստեղծիր նորին։",
    "MANUAL_NO_RECENT": "Դեռ հաճախորդներ չկան։ Սեղմիր ➕ Նոր։",
    "MANUAL_SEARCH_PROMPT": "Մուտքագրիր 2+ սիմվոլ (անուն կամ հեռախոս)։",
    "MANUAL_SEARCH_EMPTY": "Ոչինչ չգտնվեց։ Փորձիր կրկին։",
    "MANUAL_ASK_NAME": "Հաճախորդի անունը։",
    "MANUAL_NAME_BAD": "Առնվազն 2 սիմվոլ։ Փորձիր կրկին։",
    "MANUAL_ASK_PHONE": "Հաճախորդի հեռախոսահամարը (+374XXXXXXXX)։",
    "MANUAL_PHONE_BAD": "Ձևաչափը՝ +374XXXXXXXX։ Փորձիր կրկին։",
    "MANUAL_PHONE_DUP": "Այս համարով արդեն կա հաճախորդ «{name}»։ Օգտագործե՞լ նրան։",
    "MANUAL_ASK_SERVICE": "Ընտրիր ծառայությունը։",
    "MANUAL_ASK_DATE": "Ընտրիր ամսաթիվը։",
    "MANUAL_ASK_SLOT": "Ընտրիր ժամանակը կամ մուտքագրիր ոչ ստանդարտ։",
    "MANUAL_CUSTOM_PROMPT": (
        "Մուտքագրիր ամսաթիվը և ժամանակը՝ ՕՕ.ԱԱ ԺԺ:ՐՐ (կամ միայն ԺԺ:ՐՐ ընտրված ամսաթվի համար)։"
    ),
    "MANUAL_CUSTOM_BAD": "Սխալ ձևաչափ։ Օրինակ՝ 25.04 14:30",
    "MANUAL_CUSTOM_PAST": "Անցյալ ժամանակ չի կարելի ընտրել։ Ընտրիր այլ ժամանակ։",
    "MANUAL_ASK_COMMENT": "Մեկնաբանություն (կամ սեղմիր ⏭ Բաց թողնել)։",
    "MANUAL_CONFIRM_CARD": (
        "Հաստատիր գրանցումը։\n👤 {client}\n📞 {phone}\n💇 {service}\n📅 {date} {time}\n📝 {notes}"
    ),
    "MANUAL_SAVED": "✅ Գրանցումը պահպանվեց։",
    "MANUAL_CANCELED": "Չեղարկվեց։",
    "MANUAL_SLOT_TAKEN": "Այս ժամանակը հենց նոր զբաղվեց։ Ընտրիր այլը։",
    "MANUAL_BTN_SEARCH": "🔍 Որոնում",
    "MANUAL_BTN_NEW": "➕ Նոր",
    "MANUAL_BTN_SEARCH_CANCEL": "⬅ Չեղարկել որոնումը",
    "MANUAL_BTN_DUP_USE": "Այո, օգտագործել",
    "MANUAL_BTN_DUP_RETRY": "Չեղարկել — մուտքագրել այլը",
    "MANUAL_BTN_CUSTOM_TIME": "➕ Ոչ ստանդարտ ժամանակ",
    "MANUAL_BTN_BACK": "⬅ Հետ",
    "MANUAL_BTN_SKIP": "⏭ Բաց թողնել",
    "MANUAL_BTN_SAVE": "✅ Պահպանել",
    "MANUAL_BTN_CANCEL": "❌ Չեղարկել",
    # --- client-side cancellation + notification ---
    "CLIENT_NOTIFY_MANUAL": "Վարպետը ձեզ գրանցել է {date} {time} — {service}։",
    "CLIENT_CANCEL_BUTTON": "❌ Չեղարկել գրանցումը",
    "CLIENT_CANCEL_DONE": "Գրանցումը չեղարկվեց։",
    "CLIENT_CANCEL_UNAVAILABLE": "Գրանցումը արդեն հասանելի չէ։",
    "MASTER_NOTIFY_CLIENT_CANCELED": (
        "Հաճախորդը {name} չեղարկեց գրանցումը՝ {date} {time} — {service}։"
    ),
    # --- Epic 6: schedule views ---
    "SCHED_DAY_HEADER": "📅 {weekday} {dd} {mon}",
    "SCHED_WORK_HOURS_LINE": "🕐 Աշխատանքային ժամեր՝ {start}–{end}",
    "SCHED_DAY_OFF_LINE": "🕐 Այսօր հանգստյան օր է",
    "SCHED_APPTS_SECTION": "\n📋 Գրանցումներ ({count}):",
    "SCHED_APPTS_EMPTY": "\n📋 Գրանցումներ չկան։",
    "SCHED_APPT_LINE": "{emoji} {time}  {client} · {service}",
    "SCHED_FREE_SECTION": "\n🆓 Ազատ ժամանակներ։",
    "SCHED_FREE_NONE": "\n🆓 Ազատ ժամանակներ չկան։",
    "SCHED_STATUS_PENDING": "⏳",
    "SCHED_STATUS_CONFIRMED": "✅",
    "SCHED_STATUS_COMPLETED": "✅",
    "SCHED_STATUS_NO_SHOW": "❌",
    "DAY_NAV_TODAY": "⬅ Այսօր",
    "DAY_NAV_TOMORROW": "📅 Վաղը",
    "DAY_NAV_WEEK": "🗓 Շաբաթ",
    "DAY_NAV_CALENDAR": "🗓 Օրացույց",
    "DAY_NAV_ADD": "➕ Ավելացնել",
    "DAY_NAV_BACK_TO_WEEK": "⬅ Վերադառնալ շաբաթ",
    "DAY_NAV_BACK_TO_CALENDAR": "⬅ Վերադառնալ օրացույց",
    "MARK_PAST_PRESENT": "✅ {time} {short}",
    "MARK_PAST_NO_SHOW": "❌ {time} {short}",
    "MASTER_CANCEL_BTN": "❌ {time} {short}",
    "MASTER_CANCEL_ASK_FMT": (
        "Չեղարկե՞լ գրանցումը։\n\n👤 {client}\n💇 {service}\n📅 {date} {time}"
    ),
    "MASTER_CANCEL_BTN_CONFIRM": "✅ Այո, չեղարկել",
    "MASTER_CANCEL_BTN_ABORT": "← Ոչ",
    "MASTER_CANCEL_DONE": "Գրանցումը չեղարկվեց ✅",
    "MASTER_CANCEL_UNAVAILABLE": "Գրանցումն այլևս հնարավոր չէ չեղարկել։",
    "CLIENT_APPT_CANCELLED_BY_MASTER": (
        "Վարպետը չեղարկեց ձեր գրանցումը {date} {time} — {service}։\n"
        "Եթե ցանկանում եք ընտրել այլ ժամանակ՝ {link}"
    ),
    "MARK_PAST_OK_COMPLETED": "Նշված է՝ եղել է",
    "MARK_PAST_OK_NO_SHOW": "Նշված է՝ չի եկել",
    "MARK_PAST_NOT_AVAILABLE": "Գրանցումը հասանելի չէ",
    "MARK_PAST_NOT_ENDED": "Դեռ չի ավարտվել",
    "MARK_PAST_ALREADY_CLOSED": "Արդեն նշված է",
    "WEEK_HEADER": "🗓 Շաբաթը սկսած {dd} {mon}",
    "WEEK_DAY_LINE": "{wd} {dd}.{mm}  {count} գրանցում  {bar}  {pct}%",
    "WEEK_DAY_LINE_OFF": "{wd} {dd}.{mm}  հանգստյան օր  {bar}",
    "WEEK_BTN_DAY": "{wd} {dd}",
    "CLIENT_SEARCH_PROMPT": "Հաճախորդի անունը կամ հեռախոսը։",
    "CLIENT_SEARCH_TOO_SHORT": "Առնվազն 2 սիմվոլ։ Փորձիր կրկին։",
    "CLIENT_SEARCH_EMPTY": "Ոչ մեկ չգտնվեց։ Փորձիր կրկին։",
    "CLIENT_PAGE_HEADER": "👤 {name}\n📞 {phone}",
    "CLIENT_PAGE_NOTES_TITLE": "\n\n📝 Նշումներ:\n{notes}",
    "CLIENT_PAGE_NOTES_EMPTY": "_նշված չէ_",
    "CLIENT_PAGE_HISTORY_TITLE": "\n\n📊 Պատմություն ({count} գրանցում):",
    "CLIENT_PAGE_HISTORY_EMPTY": "\n\n📊 Պատմություն դեռ չկա։",
    "CLIENT_PAGE_HISTORY_LINE": "{emoji} {dd}.{mm}  {time}  {service}{suffix}",
    "CLIENT_PAGE_HISTORY_MORE": "…և ևս {n}",
    "CLIENT_PAGE_SUFFIX_FUTURE": "  · ապագա",
    "CLIENT_PAGE_SUFFIX_CANCELLED": "  · չեղարկված",
    "CLIENT_PAGE_SUFFIX_REJECTED": "  · մերժված",
    "CLIENT_PAGE_BTN_EDIT_NOTES": "✏️  Խմբագրել նշումները",
    "CLIENT_PAGE_BTN_ADD_APPT": "➕ Ավելացնել գրանցում",
    "CLIENT_PAGE_NOT_FOUND": "Հաճախորդը չի գտնվել։",
    "CLIENT_NOTES_PROMPT": "Նոր նշումներ (կամ ուղարկիր `-` մաքրելու համար)։",
    "CLIENT_NOTES_SAVED": "Պահպանվեց։",
    # --- Epic 7: reminders ---
    "REMINDER_CLIENT_DAY_BEFORE": "⏰ Հիշեցում․ վաղը {time} — {service}։\nՍպասում ենք ձեզ։",
    "REMINDER_CLIENT_TWO_HOURS": "⏰ 2 ժամից ձեր գրանցումն է՝ {service}, {time}։",
    "REMINDER_MASTER_BEFORE": "⏰ Հիմա {time}։ {client_name} — {service}։\n📞 {phone}",
    "REMINDER_PENDING_EXPIRED": (
        "Ցավոք, վարպետը չի հաստատել ձեր հայտը {date} {time} — {service}։\n"
        "Փորձեք ընտրել այլ ժամանակ՝ {link}"
    ),
    # --- Epic 9: multi-master ---
    "INVITE_CREATED_FMT": "Հրավերը ստեղծված է։\n\nԿոդ՝ `{code}`\nՀղում՝ {link}\n\nՎավերական մինչ՝ {expires}",
    "INVITE_EXPIRES_FMT": "մինչ {date}",
    "INVITE_NOT_FOUND": "Հրավերի կոդը չի գտնվել։",
    "INVITE_EXPIRED": "Հրավերի կոդը ժամկետանց է։ Խնդրեք նոր կոդ։",
    "INVITE_ALREADY_USED": "Այս կոդն արդեն օգտագործվել է։",
    "INVITE_ALREADY_MASTER": "Դուք արդեն գրանցված եք որպես վարպետ։",
    "REGISTER_ASK_SPECIALTY": "Ի՞նչ մասնագիտություն ունեք։ Սեղմեք կոճակ կամ գրեք ձերը․",
    "REGISTER_SPECIALTY_HINT_HAIR": "💈 Վարսահարդար",
    "REGISTER_SPECIALTY_HINT_DENTIST": "🦷 Ատամնաբույժ",
    "REGISTER_SPECIALTY_HINT_NAILS": "💅 Մատնահարդար",
    "REGISTER_SPECIALTY_HINT_COSMETOLOGIST": "💆 Կոսմետոլոգ",
    "REGISTER_SPECIALTY_HINT_CUSTOM": "✏️ Այլ",
    "REGISTER_SLUG_CONFIRM_FMT": "Ձեր հղումը կլինի՝\nt.me/{username}?start=master_{slug}\n\nՕգտագործե՞լ։",
    "REGISTER_SLUG_USE_BTN": "✅ Օգտագործել",
    "REGISTER_SLUG_CHANGE_BTN": "✏️ Փոխել",
    "REGISTER_ASK_CUSTOM_SLUG": "Մուտքագրեք հասցեն (միայն լատինատառ, թվեր, գծիկ, 3–32 սիմվոլ)․",
    "REGISTER_SLUG_TAKEN": "Այս հասցեն զբաղված է։ Ընտրեք այլը։",
    "REGISTER_SLUG_INVALID": "Հասցեն պետք է բաղկացած լինի լատինատառից, թվերից և գծիկներից (3–32)։",
    "REGISTER_SLUG_RESERVED": "Այս հասցեն ամրագրված է։ Ընտրեք այլը։",
    "MAIN_MENU_MY_LINK": "🔗 Իմ հղումը",
    "MAIN_MENU_QR": "📱 QR-կոդ",
    "MY_LINK_MSG_FMT": "Ձեր հղումը հաճախորդների համար՝\n{link}",
    "QR_CAPTION_FMT": "📱 Ձեր հղման QR-կոդը։\n\n{link}\n\nՏպեք և փակցրեք սրահում — հաճախորդները կսկանավորեն և միանգամից կհայտնվեն բոտում։",
    "MY_INVITES_EMPTY": "Դեռ հրավերներ չեք ստեղծել։",
    "MY_INVITES_HEADER": "Ձեր հրավերները․",
    "MY_INVITES_ITEM_FMT": "`{code}` · {status} · {expires}",
    "MY_INVITES_STATUS_ACTIVE": "ակտիվ",
    "MY_INVITES_STATUS_USED": "օգտագործված",
    "MY_INVITES_STATUS_EXPIRED": "ժամկետանց",
    "NEW_INVITE_BTN": "➕ Հրավիրել վարպետ",
    "SETTINGS_BTN_MY_LINK": "🔗 Իմ հղումը",
    "SETTINGS_BTN_MY_INVITES": "📨 Իմ հրավերները",
    "SETTINGS_BTN_NEW_INVITE": "➕ Հրավիրել վարպետ",
    "SETTINGS_BTN_PROFILE": "👤 Իմ պրոֆիլը",
    "SETTINGS_BTN_ADMIN": "🛠 Ադմին",
    "PROFILE_MENU_TITLE": "Ի՞նչ փոխել։",
    "PROFILE_BTN_NAME": "✏️ Անուն",
    "PROFILE_BTN_SPECIALTY": "✏️ Մասնագիտություն",
    "PROFILE_BTN_SLUG": "✏️ Հասցե (slug)",
    "PROFILE_ASK_NEW_NAME": "Մուտքագրեք նոր անունը․",
    "PROFILE_ASK_NEW_SPECIALTY": "Մուտքագրեք մասնագիտությունը․",
    "PROFILE_ASK_NEW_SLUG": "Մուտքագրեք նոր հասցեն (3–32 սիմվոլ)․",
    "PROFILE_UPDATED": "Պատրաստ է ✅",
    "CLIENT_CATALOG_HEADER": "Ընտրեք վարպետ․",
    "CLIENT_CATALOG_EMPTY": "Վարպետներ դեռ գրանցված չեն։",
    "CLIENT_CATALOG_CARD_FMT": "👤 {name} — {specialty}",
    "CLIENT_CATALOG_PICK_BTN": "📅 Գրանցվել",
    "CLIENT_MASTER_NOT_FOUND": "Վարպետ չի գտնվել։",
    "CLIENT_MASTER_CARD_FMT": "👤 {name}\n{specialty}",
    "CLIENT_BOOK_HERE_BTN": "📅 Գրանցվել",
    "MASTER_BLOCKED_BANNER": "⛔ Ձեր կաբինետը ժամանակավոր արգելափակված է ադմինիստրատորի կողմից։",
    "CLIENT_APPT_REJECTED_BLOCK": "Ցավոք, վարպետն այս պահին հասանելի չէ։ Ձեր դիմումը չեղարկված է։",
    "ADMIN_MENU_TITLE": "Ադմին մենյու․",
    "ADMIN_MENU_MASTERS": "👥 Վարպետներ",
    "ADMIN_MENU_STATS": "📊 Վիճակագրություն",
    "ADMIN_MENU_INVITES": "📨 Հրավերներ",
    "ADMIN_MENU_MODERATION": "🛠 Մոդերացիա",
    "ADMIN_MENU_BACK": "⬅️ Գլխավոր մենյու",
    "ADMIN_MASTERS_HEADER": "Բոլոր վարպետները․",
    "ADMIN_MASTERS_EMPTY": "Վարպետներ դեռ չկան։",
    "ADMIN_MASTER_ITEM_FMT": "`{slug}` · {name} · {status}",
    "ADMIN_MASTER_STATUS_ACTIVE": "ակտիվ",
    "ADMIN_MASTER_STATUS_BLOCKED": "արգելափակված",
    "ADMIN_BLOCK_BTN": "🚫 Արգելափակել",
    "ADMIN_UNBLOCK_BTN": "✅ Վերականգնել",
    "ADMIN_BLOCK_DONE_FMT": "Վարպետը {slug} արգելափակված է։ Չեղարկված pending՝ {n}։",
    "ADMIN_UNBLOCK_DONE_FMT": "Վարպետը {slug} վերականգնված է։",
    "ADMIN_STATS_FMT": (
        "📊 Վիճակագրություն\n\n"
        "Վարպետներ՝ {masters_active} ակտիվ / {masters_blocked} արգելափակված\n"
        "Հաճախորդներ (ունիկալ)՝ {clients}\n"
        "Գրանցումներ 7 օրում՝ {appt_7d}\n"
        "Գրանցումներ 30 օրում՝ {appt_30d}"
    ),
    "ADMIN_INVITES_HEADER": "Բոլոր հրավերները․",
    "ADMIN_INVITE_ITEM_FMT": "`{code}` · {status} · {creator_tg_id}-ի կողմից",
    "ADMIN_INVITE_NEW_SALON_BTN": "➕ Հրավիրել սրահ",
    "ADMIN_INVITE_SALON_CREATED_FMT": (
        "Սրահի հրավերը ստեղծված է։\n\nԿոդ՝ `{code}`\nՀղում՝ {link}\nՎավերական մինչ՝ {expires}"
    ),
    "ADMIN_MASTER_NOT_FOUND": "Այս slug-ով վարպետ չի գտնվել։",
    "ADMIN_MASTER_DETAIL_REGISTERED": "Գրանցված է",
    "ADMIN_MASTER_DETAIL_SPECIALTY": "Մասնագիտություն",
    "ADMIN_MASTER_DETAIL_STATUS": "Կարգավիճակ",
    "ADMIN_MASTER_USAGE": "Օգտագործում՝ /master <slug>",
    # --- Epic 10.1: salon main menu ---
    "SALON_WELCOME_BACK": "Բարի վերադարձ, սրահ։",
    "SALON_MENU_MY_MASTERS": "👥 Իմ վարպետները",
    "SALON_MENU_INVITE_MASTER": "➕ Հրավիրել վարպետ",
    "SALON_MENU_ADD_APPT": "➕ Նոր գրանցում",
    "SALON_MENU_MY_LINK": "🔗 Իմ հղումը",
    "SALON_MENU_QR": "📱 QR-կոդ",
    "SALON_MENU_SETTINGS": "⚙️ Կարգավորումներ",
}

_BUNDLES: dict[str, dict[str, Any]] = {"ru": _RU, "hy": _HY}


class _StringsProxy:
    """Module-like proxy: `strings.REGISTER_WELCOME` resolves against the current lang."""

    def __getattr__(self, key: str) -> Any:
        bundle = _BUNDLES.get(get_current_lang(), _RU)
        try:
            return bundle[key]
        except KeyError as exc:
            # Fall back to RU so a missing HY key doesn't crash the bot.
            if key in _RU:
                return _RU[key]
            raise AttributeError(key) from exc


strings: Any = _StringsProxy()


def get_bundle(lang: str) -> SimpleNamespace:
    """For tests / ad-hoc access to a language bundle without touching the ContextVar."""
    return SimpleNamespace(**_BUNDLES.get(lang, _RU))
